version: '3.8'

services:
  database:
    image: postgres:15
    container_name: dev_eval_db
    restart: always
    environment:
      POSTGRES_DB: DevEvalDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
